---
- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 86400
  ignore_errors: yes
  when: ansible_os_family == 'Debian'

- name: Update yum packages
  yum:
    update_cache: yes
  when: ansible_os_family == 'RedHat'
  ignore_errors: yes

- name: Install package depends | pre-setup
  package:
    name: "{{ cycloid_packages_list }}"
    state: present

- locale_gen: name=fr_FR.UTF-8 state=present
  when: ansible_os_family == 'Debian'

- name: "Vim config file"
  copy: src=vimrc
        dest=/etc/vim/vimrc
  when: ansible_os_family == 'Debian'

- name: "Vim config file"
  copy: src=vimrc
        dest=/etc/vimrc
  when: ansible_os_family == 'RedHat'

- group: name=admin state=present
- user: name=admin group=admin shell=/bin/bash state=present skeleton=/etc/skel

- name: Install extra list of packages
  package:
    name: "{{ base_extra_packages }}"
    state: present
  when: base_extra_packages|length > 0

- name: Install extra list of pip packages
  pip:
    name: "{{ base_extra_pip_packages }}"
    state: present
  when: base_extra_pip_packages|length > 0
